name: 'Update Your README'
description: 'Automatically suggest updates to your README based on pull request changes.'
author: 'Keith and Lara'

inputs:
  github-token:
    description: 'GitHub Token to authenticate the action.'
    required: true
  anthropic-api-key:
    description: 'Anthropic API Key (we use their LLM APIs to generate the README updates).'
    required: true
  # TODO: This should be inferred from the github context
  repository:
    description: 'The repository where the pull request was opened.'
    required: true
  # TODO: This should be inferred from the github context
  pull-request-number:
    description: 'The number of the pull request to process.'
    required: true
  readme-file:
    description: 'The path to the README file to update.'
    required: false
    default: 'README.md'

runs:
  using: "composite"
  steps:
    # Print the current directory and list files
    - name: Show file system
      shell: bash
      run: |
        echo "Current directory"
        pwd
        ls -F
        echo "Action directory"
        cd ${{ github.action_path }}
        pwd
        ls -F

    - name: Show github context object
      run: |
        cat << OBJECT
        ${{ toJson(github) }}
        OBJECT

    # Checkout the repository (TODO: Use the version pinned in the workflow)
    # - name: Check out ktrnka/update-your-readme
    #   uses: actions/checkout@v4
    #   with:
    #     repository: ktrnka/update-your-readme
    #     path: ktrnka/update-your-readme

    # Note: It's already checked out into ${{ github.action_path }}

    # Change directory to the cloned repository
    # - name: Change directory
    #   shell: bash
    #   run: cd ktrnka/update-your-readme

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    # Install dependencies
    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    # Run the core logic to update the README
    # NOTE: Beware the ../..
    - name: Update README
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        pipenv run python src/core.py \
        --repository ${{ inputs.repository }} \
        --pr ${{ inputs.pull-request-number }} \
        --readme ${{ github.workspace }}/${{ inputs.readme-file }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
    
    # Create a new PR with README changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      id: cpr
      with:
        token: ${{ inputs.github-token }}
        commit-message: Updated README
        title: "[Bot] README updates for PR ${{ inputs.pull-request-number }}"
        body: >
          This PR is auto-generated by
          [update-your-readme](https://github.com/ktrnka/update-your-readme).
          The README changes are generated based on the changes in PR ${{ github.event.pull_request.html_url }} and
          your existing README.
        labels: feature, automated pr
        branch: "update-your-readme-${{ inputs.pull-request-number }}"
        base: ${{ github.event.pull_request.head.ref }}
        reviewers: ${{ github.event.pull_request.user.login }}
        add-paths: ${{ inputs.readme-file }}

    # Comment on the original PR with a link to the newly created PR
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      if: steps.cpr.outputs.pull-request-url != ''
      with:
        token: ${{ inputs.github-token }}
        issue-number: ${{ inputs.pull-request-number }}
        body: |
          Suggested README changes in PR ${{ steps.cpr.outputs.pull-request-url }}

branding:
  icon: 'book-open'
  color: 'purple'
