name: 'Update Your README'
description: 'Automatically suggest updates to your README based on pull request changes.'
author: 'Keith and Lara'

inputs:
  model-provider: 
    description: 'Model provider to use. (anthropic, openai, or github)'
    required: true
    default: 'anthropic'
  api-key:
    description: 'API Key for the specified model provider.'
    required: true
  model:
    description: 'Model to use.'
    required: true
    default: 'claude-3-5-sonnet-20240620'
  readme-file:
    description: 'The path to the README file to update.'
    required: true
    default: 'README.md'
  debug:
    description: 'Enable debug mode.'
    required: false
    default: 'false'
  pr-labels:
    description: 'Comma-separated list of labels to add on README PRs.'
    required: false
    default: 'documentation, update-your-readme'

runs:
  using: "composite"
  steps:
    # Print the current directory and list files
    - name: Show file system
      if: inputs.debug != 'false'
      shell: bash
      run: |
        echo "Current directory"
        pwd
        ls -F
        echo "Action directory"
        cd ${{ github.action_path }}
        pwd
        ls -F

    # Echo some key context variables
    - name: Show non-secret inputs
      if: inputs.debug != 'false'
      shell: bash
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Pull Request Number: ${{ github.event.pull_request.number }}"
        echo "README File: ${{ inputs.readme-file }}"

    # Show the key paths from the context
    - name: Show context paths
      if: inputs.debug != 'false'
      shell: bash
      run: |
        echo "Repository path: ${{ github.workspace }}"
        echo "Action path": ${{ github.action_path }}

    # Fail fast if the API key is empty
    - name: Check API Key
      if: ${{ inputs.api-key == '' }}
      shell: bash
      run: |
        echo "Error: api-key is required."
        exit 1

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      shell: bash
      working-directory: ${{ github.action_path }}
      run: uv python install

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: make install

    # Run the core logic to update the README
    - name: Update README
      id: update-readme
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        uv run python src/main.py \
        --repository ${{ github.repository }} \
        --pr ${{ github.event.pull_request.number }} \
        --readme ${{ github.workspace }}/${{ inputs.readme-file }} \
        --model-provider ${{ inputs.model-provider }} \
        --model ${{ inputs.model }} \
        --output-format github \
        >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ github.token }}
        API_KEY: ${{ inputs.api-key }}
    
    # Create a new PR with README changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      id: cpr
      with:
        token: ${{ github.token }}
        commit-message: Updated README
        title: "[Bot] README updates for PR ${{ github.event.pull_request.number }}"
        body: >
          ${{ steps.update-readme.outputs.reason }}

          This PR is auto-generated by
          [update-your-readme](https://github.com/ktrnka/update-your-readme).
          The README changes are generated based on the changes in PR ${{ github.event.pull_request.html_url }} and
          your existing README.
        labels: ${{ inputs.pr-labels }}
        branch: "update-your-readme-${{ github.event.pull_request.number }}"
        base: ${{ github.event.pull_request.head.ref }}
        reviewers: ${{ github.event.pull_request.user.login }}
        add-paths: ${{ inputs.readme-file }}

    # Comment on the original PR with a link to the newly created PR
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      if: steps.cpr.outputs.pull-request-url != ''
      with:
        token: ${{ github.token }}
        issue-number: ${{ github.event.pull_request.number }}
        body: >
          Suggested README update: ${{ steps.cpr.outputs.pull-request-url }}

          Reason:
          ${{ steps.update-readme.outputs.reason }}


branding:
  icon: 'book-open'
  color: 'purple'
