name: 'Update Your README'
description: 'Automatically suggest updates to your README based on pull request changes.'
author: 'Keith and Lara'

inputs:
  github-token:
    description: 'GitHub Token to authenticate the action.'
    required: true
  anthropic-api-key:
    description: 'Anthropic API Key (we use their LLM APIs to generate the README updates).'
    required: true
  # # TODO: This should be inferred from the github context
  # repository:
  #   description: 'The repository where the pull request was opened.'
  #   required: true
  # # TODO: This should be inferred from the github context
  # pull-request-number:
  #   description: 'The number of the pull request to process.'
  #   required: true
  readme-file:
    description: 'The path to the README file to update.'
    required: false
    default: 'README.md'

runs:
  using: "composite"
  steps:
    # Print the current directory and list files
    - name: Show file system
      shell: bash
      run: |
        echo "Current directory"
        pwd
        ls -F
        echo "Action directory"
        cd ${{ github.action_path }}
        pwd
        ls -F

    # Echo some key context variables
    - name: Show non-secret inputs
      shell: bash
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Pull Request Number: ${{ github.event.pull_request.number }}"
        echo "README File: ${{ inputs.readme-file }}"

    # Show the key paths from the context
    - name: Show context paths
      shell: bash
      run: |
        echo "Repository path: ${{ github.workspace }}"
        echo "Action path": ${{ github.action_path }}

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    # Install dependencies
    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    # Run the core logic to update the README
    - name: Update README
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        pipenv run python src/core.py \
        --repository ${{ github.repository }} \
        --pr ${{ github.event.pull_request.number }} \
        --readme ${{ github.workspace }}/${{ inputs.readme-file }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
    
    # Create a new PR with README changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      id: cpr
      with:
        token: ${{ inputs.github-token }}
        commit-message: Updated README
        title: "[Bot] README updates for PR ${{ inputs.pull-request-number }}"
        body: >
          This PR is auto-generated by
          [update-your-readme](https://github.com/ktrnka/update-your-readme).
          The README changes are generated based on the changes in PR ${{ github.event.pull_request.html_url }} and
          your existing README.
        labels: feature, automated pr
        branch: "update-your-readme-${{ inputs.pull-request-number }}"
        base: ${{ github.event.pull_request.head.ref }}
        reviewers: ${{ github.event.pull_request.user.login }}
        add-paths: ${{ inputs.readme-file }}

    # Comment on the original PR with a link to the newly created PR
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      if: steps.cpr.outputs.pull-request-url != ''
      with:
        token: ${{ inputs.github-token }}
        issue-number: ${{ inputs.pull-request-number }}
        body: |
          Suggested README changes in PR ${{ steps.cpr.outputs.pull-request-url }}

branding:
  icon: 'book-open'
  color: 'purple'
