name: Close stale README PRs

on:
  pull_request:
    types:
      - closed

jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Close dependent README PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: src/close_stale_prs.sh ${{ github.event.pull_request.number }}
