name: Close stale README PRs

on:
  pull_request:
    types:
      - closed

jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Close dependent README PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: src/close_stale_prs.sh
