name: Review for README updates

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Note: This points to the latest version on main; users should pull a tagged version instead
      # When doing development on a branch, point to the branch
      - uses: ktrnka/update-your-readme@portability
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          repository: ${{ github.repository }}
          pull-request-number: ${{ github.event.pull_request.number }}
          readme-file: README.md
