# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Suggest README updates

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Update README
      run: echo "This is a suggestion for the README" > README.md
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Get PR author
      id: pr-author
      run: |
        PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        echo "author=$PR_AUTHOR" >> $GITHUB_OUTPUT
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Updated README
        title: '[Testing] Updating README'
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: feature, automated pr
        branch: update-your-readme
        branch-suffix: timestamp
        base: ${{ steps.extract_branch.outputs.branch }}
        reviewers: ${{ steps.pr-author.outputs.author }}

