name: Review for README updates

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      # Note: This points to the latest version on main; users should pull a tagged version instead
      # When doing development on a branch, point to the branch
      # The "uses" field doesn't support variables, so we can't use the branch name dynamically
      - uses: ktrnka/update-your-readme@uv-packaging
        with:
          model-provider: "openai"
          model: gpt-4o-mini-2024-07-18
          api-key: ${{ secrets.OPENAI_API_KEY }}
          readme-file: README.md
          debug: "true"
