
name: Review for README updates

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: pipenv run python src/core.py --repository ${GITHUB_REPOSITORY} --pr ${{ github.event.pull_request.number }} > README.md
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Get PR author
        id: pr-author
        run: |
          PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          echo "author=$PR_AUTHOR" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updated README
          title: "[Bot] README updates for PR ${{ github.event.pull_request.number }}"
          body: >
            This PR is auto-generated by
            [update-your-readme](https://github.com/ktrnka/update-your-readme).
            The README changes are generated based on the changes in PR ${{ github.event.pull_request.url }} and
            your existing README.
          labels: feature, automated pr
          branch: "update-your-readme-${{ github.event.pull_request.number }}"
          base: ${{ steps.extract_branch.outputs.branch }}
          reviewers: ${{ steps.pr-author.outputs.author }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Suggested README changes in PR ${{ steps.cpr.outputs.pull-request-url }}
